// examples/react/src/App.tsx
import { useState, useRef } from 'react';
import '@an-sajinsatheesan/fable-editor/style.css';
import { FableEditor } from '@an-sajinsatheesan/fable-editor/react';
import type { FableEditorApi } from '@an-sajinsatheesan/fable-editor';

function App() {
  const [value, setValue] = useState('<p><strong>React wrapper</strong> is working.</p>');
  const [language, setLanguage] = useState<'en' | 'ar'>('en');
  const editorRef = useRef<FableEditorApi>(null);

  return (
    <div style={{ maxWidth: 1000, margin: '30px auto', padding: '0 20px' }}>
      <h2>FableEditor — React test</h2>
      <div style={{ marginBottom: 12 }}>
        <button onClick={() => setLanguage('en')} disabled={language === 'en'}>
          English
        </button>{' '}
        <button onClick={() => setLanguage('ar')} disabled={language === 'ar'}>
          العربية
        </button>{' '}
        <button onClick={() => console.log(editorRef.current?.getContent())}>
          Log content
        </button>{' '}
        <button onClick={() => editorRef.current?.setContent('<p>Reset content</p>')}>
          Reset
        </button>
      </div>
      <FableEditor
        ref={editorRef}
        value={value}
        onChange={setValue}
        language={language}
        height={400}
      />
      <h3>HTML output</h3>
      <pre style={{ background: '#f4f4f4', padding: 12, borderRadius: 6 }}>
        {value}
      </pre>
    </div>
  );
}

export default App;

// examples/angular/src/app/app.component.ts
import { Component } from '@angular/core';
import { FableEditorModule } from '@an-sajinsatheesan/fable-editor/angular';

@Component({
  selector: 'app-root',
  standalone: true,
  imports: [FableEditorModule],
  templateUrl: './app.component.html',
  styleUrl: './app.component.css'
})
export class AppComponent {
  content = '<p><strong>Angular wrapper</strong> is working.</p>';
  language: 'en' | 'ar' = 'en';

  onChange(content: string) {
    this.content = content;
  }

  logContent(editor: { getContent(): string }) {
    console.log(editor.getContent());
  }
}

<div style="max-width: 1000px; margin: 30px auto; padding: 0 20px;">
  <h2>FableEditor — Angular test</h2>
  <div style="margin-bottom: 12px;">
    <button (click)="language = 'en'" [disabled]="language === 'en'">English</button>
    <button (click)="language = 'ar'" [disabled]="language === 'ar'">العربية</button>
    <button (click)="logContent(editor)">Log content</button>
    <button (click)="editor.setContent('<p>Reset content</p>')">Reset</button>
  </div>
  <fable-editor
    #editor
    [value]="content"
    (editorChange)="onChange($event)"
    [language]="language"
    [height]="400"
  ></fable-editor>
  <h3>HTML output</h3>
  <pre style="background: #f4f4f4; padding: 12px; border-radius: 6px;">{{ content }}</pre>
</div>
