// src/angular/fable-editor.component.ts
import {
  Component,
  ElementRef,
  EventEmitter,
  Input,
  OnChanges,
  OnDestroy,
  OnInit,
  Output,
  SimpleChanges,
  ViewChild
} from '@angular/core';
import { FableEditor, EditorInitOptions, EditorLanguage, FableEditorApi } from '../core';

@Component({
  selector: 'fable-editor',
  standalone: true,
  template: `<div #container></div>`,
  styles: [':host { display: block; }']
})
export class FableEditorComponent implements OnInit, OnChanges, OnDestroy {
  @ViewChild('container', { static: true }) container!: ElementRef<HTMLDivElement>;

  @Input() language: EditorLanguage = 'en';
  @Input() height = 302;
  @Input() menubar: boolean | string = true;
  @Input() toolbar: boolean | string = true;
  @Input() statusbar = true;
  @Input() readonly = false;
  @Input() init: Partial<Omit<EditorInitOptions, 'target'>> = {};
  @Input() value = '';

  @Output() editorChange = new EventEmitter<string>();
  @Output() editorReady = new EventEmitter<FableEditorApi>();

  private editor?: FableEditor;
  private lastContent = '';

  ngOnInit(): void {
    this.lastContent = this.value;
    this.editor = new FableEditor({
      target: this.container.nativeElement,
      language: this.language,
      height: this.height,
      menubar: this.menubar,
      toolbar: this.toolbar,
      statusbar: this.statusbar,
      readonly: this.readonly,
      initialContent: this.value,
      ...this.init,
      onChange: (content) => {
        this.lastContent = content;
        this.editorChange.emit(content);
      },
      onReady: (api) => this.editorReady.emit(api)
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (!this.editor) return;
    if (changes['language'] && !changes['language'].firstChange) {
      this.editor.setLanguage(this.language);
    }
    if (changes['value'] && !changes['value'].firstChange && this.value !== this.lastContent) {
      this.lastContent = this.value;
      this.editor.setContent(this.value ?? '');
    }
  }

  ngOnDestroy(): void {
    this.editor?.destroy();
    this.editor = undefined;
  }

  getContent(): string {
    return this.editor?.getContent() ?? '';
  }

  setContent(html: string): void {
    this.lastContent = html;
    this.editor?.setContent(html ?? '');
  }

  insertContent(html: string): void {
    this.editor?.insertContent(html);
  }

  setLanguage(lang: EditorLanguage): void {
    this.editor?.setLanguage(lang);
  }

  focus(): void {
    this.editor?.focus();
  }

  writeValue(value: string): void {
    this.editor?.setContent(value ?? '');
  }
}

// src/react/FableEditor.tsx
import React, { useEffect, useImperativeHandle, useRef, forwardRef } from 'react';
import { FableEditor as FableEditorCore, EditorInitOptions, EditorLanguage, FableEditorApi } from '../core';

export interface FableEditorProps extends Omit<EditorInitOptions, 'target' | 'onChange' | 'onReady'> {
  value?: string;
  defaultValue?: string;
  onChange?: (content: string) => void;
  onReady?: (editor: FableEditorApi) => void;
  className?: string;
  style?: React.CSSProperties;
}

export const FableEditor = forwardRef<FableEditorApi, FableEditorProps>(
  ({ value, defaultValue, onChange, onReady, className, style, ...initOptions }, ref) => {
    const containerRef = useRef<HTMLDivElement>(null);
    const editorRef = useRef<FableEditorCore | null>(null);
    const isInternalChange = useRef(false);
    const lastValue = useRef(value ?? defaultValue);
    const onChangeRef = useRef(onChange);
    const onReadyRef = useRef(onReady);

    onChangeRef.current = onChange;
    onReadyRef.current = onReady;

    useImperativeHandle(ref, () => ({
      getContent: () => editorRef.current?.getContent() ?? '',
      setContent: (html: string) => editorRef.current?.setContent(html),
      insertContent: (html: string) => editorRef.current?.insertContent(html),
      setLanguage: (lang: EditorLanguage) => editorRef.current?.setLanguage(lang),
      focus: () => editorRef.current?.focus(),
      destroy: () => editorRef.current?.destroy(),
      importWordFile: (file: File) => editorRef.current?.importWordFile(file) ?? Promise.resolve(),
      restoreDraft: () => editorRef.current?.restoreDraft() ?? false,
      getRevisions: () => editorRef.current?.getRevisions() ?? []
    }));

    useEffect(() => {
      if (!containerRef.current) return;
      const editor = new FableEditorCore({
        target: containerRef.current,
        initialContent: lastValue.current,
        onChange: (content) => {
          isInternalChange.current = true;
          lastValue.current = content;
          onChangeRef.current?.(content);
        },
        onReady: (api) => onReadyRef.current?.(api),
        ...initOptions
      });
      editorRef.current = editor;

      return () => {
        editor.destroy();
        editorRef.current = null;
      };
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    useEffect(() => {
      if (value === undefined) return;
      if (value === lastValue.current) return;
      if (isInternalChange.current) {
        isInternalChange.current = false;
        return;
      }
      lastValue.current = value;
      editorRef.current?.setContent(value);
    }, [value]);

    useEffect(() => {
      if (initOptions.language) {
        editorRef.current?.setLanguage(initOptions.language);
      }
    }, [initOptions.language]);

    return <div ref={containerRef} className={className} style={style} />;
  }
);

FableEditor.displayName = 'FableEditor';
